### PR TITLE
(refactor) FormField attribute 'Type' should be Optional

### PR DESCRIPTION
**Pull request by Twiineenock**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Markdown questions have no question `type` hence should be optional in the form `schema`.
This related to the work coming in from here [We should make this optional since markdown content doesn't have a type](https://github.com/openmrs/openmrs-esm-form-builder/pull/355#discussion_r1816594802)

### CODE REVIEW

**Review by NethmiRodrigo — APPROVED** [review]
LGTM! @samuelmale we had to make type optional as well. Does that seem okay?

**Comment by samuelmale** [comment]
This makes sense and I'm not opposed to the idea. 

> Markdown questions have no question type hence should be optional in the form schema

The FE defines a pseudo type called `control` ([see](https://github.com/openmrs/openmrs-esm-form-engine-lib/blob/main/src/adapters/control-adapter.ts)) and I believe it should be used in such scenarios. If this makes sense, we can have this type as a reasonable default in the form-builder. cc: @denniskigen

```json
           {
             "type": "control"
              "value": [
                "**This form is used to**:showcase feature of the react form engine",
                "### This is just an **explainer text** example  in *markdown*"
              ],
              "questionOptions": {
                "rendering": "markdown"
              },
              "id": "heading2"
            }
```

**Comment by denniskigen** [comment]
Seems reasonable to me, @samuelmale!

**Comment by NethmiRodrigo** [comment]
@samuelmale that makes sense! Shall we opt to do that instead then, default `type` to the value `control`, without making it optional? FYI @Twiineenock

**Comment by NethmiRodrigo** [comment]
Closing this PR in favor of making the `type` to `control` for markdown content

**Pull request closed without merging**
