### PR TITLE
(fix) O3-3503: Fix pagination of problem datasource fetch results

### PR DESCRIPTION
**Pull request by CynthiaKamau**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Currently, the implementation of the problem data source fetches only 50 results due to pagination constraints. This limitation affects the visibility of data across three concept classes. This pull request aims to enhance the data fetching process to retrieve all results from the endpoint, ensuring comprehensive data coverage.

## Screenshots

https://github.com/openmrs/openmrs-form-engine-lib/assets/19533785/b81e82b4-6f04-4359-9486-7a1414d67096

## Related Issue

https://openmrs.atlassian.net/browse/O3-3503

### CODE REVIEW

**Comment by samuelmale** [comment]
Loading all available concepts appears to be very resource-intensive. I suggest implementing a "background search" that uses user input as the search term.

**Comment by CynthiaKamau** [comment]
> Loading all available concepts appears to be very resource-intensive. I suggest implementing a "background search" that uses user input as the search term.

This will be a bit hard given that `problems ` come from three different concept classes, also for questions that use  problems as obs, search might not work

**Comment by samuelmale** [comment]
This would work perfectly for a single concept class:

```ts

const searchTerm = "WHO";

/openmrs/ws/rest/v1/concept?searchType=fuzzy&v=custom:(uuid,display,conceptClass:(uuid,display))&class=8d4918b0-c2cc-11de-8d13-0010c6dffd0f&q=${searchTerm}

```

To support multiple classes I think we can filter the returned results by the classes:

```ts
const classes = [
  '8d4918b0-c2cc-11de-8d13-0010c6dffd0f',
  '8d492954-c2cc-11de-8d13-0010c6dffd0f',
  '8d492b2a-c2cc-11de-8d13-0010c6dffd0f'
];

const url = `${restBaseUrl}/concept?searchType=fuzzy&v=custom:(uuid,display,conceptClass:(uuid,display))&q=${searchTerm}`;

openmrsFetch(url).then(({ data }) => {
  return data.results.filter(
    (concept) => classes.includes(concept.conceptClass.uuid)
  );
});
```

**Comment by CynthiaKamau** [comment]
> This would work perfectly for a single concept class:
> 
> ```ts
> const searchTerm = "WHO";
> 
> /openmrs/ws/rest/v1/concept?searchType=fuzzy&v=custom:(uuid,display,conceptClass:(uuid,display))&class=8d4918b0-c2cc-11de-8d13-0010c6dffd0f&q=${searchTerm}
> ```
> 
> To support multiple classes I think we can filter the returned results by the classes:
> 
> ```ts
> const classes = [
>   '8d4918b0-c2cc-11de-8d13-0010c6dffd0f',
>   '8d492954-c2cc-11de-8d13-0010c6dffd0f',
>   '8d492b2a-c2cc-11de-8d13-0010c6dffd0f'
> ];
> 
> const url = `${restBaseUrl}/concept?searchType=fuzzy&v=custom:(uuid,display,conceptClass:(uuid,display))&q=${searchTerm}`;
> 
> openmrsFetch(url).then(({ data }) => {
>   return data.results.filter(
>     (concept) => classes.includes(concept.conceptClass.uuid)
>   );
> });
> ```

The issue with searching through the results is that the data returned contains 50 results, and if you filter, you will only get one result, unless the limit is increased, which will still not return the expected results

**Comment by samuelmale** [comment]
Makes sense. @ibacher should we consider supporting multiple concept classes ([here](https://github.com/openmrs/openmrs-module-webservices.rest/blob/fcc0ee7380d8e1ac861204d68e82d812f39bb1aa/omod-1.8/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/search/openmrs1_8/ConceptSearchHandler1_8.java#L123-L129)) for fuzzy searches?

**Comment by samuelmale** [comment]
Since we lack the ideal backend support, I think @CynthiaKamau's solution can work for now ie. fetching concepts of all the classes in parallel.

Question: Does this problem exist in AFE?

**Comment by CynthiaKamau** [comment]
> Since we lack the ideal backend support, I think @CynthiaKamau's solution can work for now ie. fetching concepts of all the relevant classes in parallel.
> 
> Question: Does this problem exist in AFE?

In AFE, diagnosis/problems are handled as a datasource, so 

> ```ts
> /concept?searchType=
> ```

In AFE, the input is searchable, in RFE, there instances where its a select box

**Comment by samuelmale** [comment]
>In AFE, the input is searchable, in RFE, there instances where its a select box

The IIRC the ui-select-ext supports searching, can we instead switch to doing a search? cc: @kajambiya

**Comment by samuelmale** [comment]
Filed ticket: https://openmrs.atlassian.net/browse/O3-3770

**Comment by mogoodrich** [comment]
Actually @brandones  @samuelmale ... @chibongho  just recently merged the following PR, worth taking a look at: https://github.com/openmrs/openmrs-esm-core/commit/45bdc9b94c44175bd7ffa9ebf9029462feafda80

**Comment by samuelmale** [comment]
> Actually @brandones @samuelmale ... @chibongho just recently merged the following PR, worth taking a look at: https://github.com/openmrs/openmrs-esm-core/commit/45bdc9b94c44175bd7ffa9ebf9029462feafda80

Thanks for sharing, @mogoodrich. I think this is particularly useful when dealing with paginable components like data tables.

> What should we do about this PR? Close in favor of doing O3-3770? Merge until we have a better solution?

@brandones I’m inclined to implement or fix the search capability rather than eagerly loading all concepts from different classes in one shot.

**Comment by CynthiaKamau** [comment]
> Ok, thanks @samuelmale . @CynthiaKamau , will you do that, do you have the time?

Yes, working on updating it

**Comment by CynthiaKamau** [comment]
> > Actually @brandones @samuelmale ... @chibongho just recently merged the following PR, worth taking a look at: [openmrs/openmrs-esm-core@45bdc9b](https://github.com/openmrs/openmrs-esm-core/commit/45bdc9b94c44175bd7ffa9ebf9029462feafda80)
> 
> Thanks for sharing, @mogoodrich. I think this is particularly useful when dealing with paginable components like data tables.
> 
> > What should we do about this PR? Close in favor of doing O3-3770? Merge until we have a better solution?
> 
> @brandones I’m inclined to implement or fix the search capability rather than eagerly loading all concepts from different classes in one shot.

@samuelmale would switching to this format suffice , i wouldn't really need to make any changes ?
```
{
              "label": "Test problem",
              "type": "obs",
              "id": "patient_transfer_location",
              "questionOptions": {
                "rendering": "ui-select-extended",
                "isSearchable": true,
                "concept": "160540AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
                "datasource": {
                  "name": "problem_datasource"
                }
              }
            }
```

**Comment by samuelmale** [comment]
@CynthiaKamau The question configuration looks okay; does it work as expected?

**Comment by CynthiaKamau** [comment]
> @CynthiaKamau The question configuration looks okay; does it work as expected?

Is it related to [ this](https://openmrs.atlassian.net/browse/O3-3770) ticket ?

**Comment by samuelmale** [comment]
> 
> Is it related to [ this](https://openmrs.atlassian.net/browse/O3-3770) ticket ?

Affirmative! I also noticed that you're working on the talked about ticket.

**Pull request closed without merging**
